---
# Prepare server for CI-pipeline
# This playbook adds a NOPASSWD entry in the sudoers file, forbit ssh password authentification,
# creates a user 'ansible' and deletes the start user (inclusive home).

- hosts: localhost
  tasks:
  - name: Create ssh key
    user:
      name: "{{ lookup('env','USER') }}"
      generate_ssh_key: yes
      ssh_key_bits: 8192      
      append: yes 

- hosts: pipe
  become: yes 
  tasks:
  - name: Remove wheel group from sudo
    lineinfile:
      path: /etc/sudoers
      state: absent
      regexp: '^%wheel'
      validate: '/usr/sbin/visudo -cf %s'
  - name: Remove wheel group from /etc/groups
    group:
      name: wheel
      state: absent
  - name: Add a NOPASSWD entry in the sudoers file
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%sudo\s*ALL='
      line: '%sudo ALL=(ALL) NOPASSWD: ALL'
      validate: '/usr/sbin/visudo -cf %s'
  - name: Adduser 'ansible'
    user:
      name: ansible
      comment: technical ansible user
      groups: sudo, docker
      home: /msr/people/ansible
      shell: /bin/bash
      append: yes    
  - name: Set authorized key took from file
    authorized_key:
      user: ansible
      state: present
      key: "{{ lookup('file', '~{{user.stdout}}/.ssh/id_rsa.pub') }}"
      
  roles:
  - sshd
#
# eof ..
