---
# Prepare server for CI-pipeline
# This playbook adds a NOPASSWD entry in the sudoers file, forbit ssh password authentification,
# creates a user 'ansible' and deletes the start user (inclusive home).

- hosts: pipe
  tasks:
  - name: Add a NOPASSWD entry in the sudoers file
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%SUDO ALL='
      line: '%SUDO ALL=(ALL) NOPASSWD: ALL'
      validate: '/usr/sbin/visudo -cf %s'
#
# eof ..
