---
# Prepare server for CI-pipeline
# This playbook adds a NOPASSWD entry in the sudoers file, forbit ssh password authentification,
# creates a user 'ansible' and deletes the start user (inclusive home).

- hosts: pipe
  become: yes 
  tasks:
  - name: Remove wheel group from sudo
    lineinfile:
      path: /etc/sudoers
      state: absent
      regexp: '^%wheel'
      validate: '/usr/sbin/visudo -cf %s'
  - name: Remove wheel group from /etc/groups
    group:
      name: wheel
      state: absent
  - name: Add a NOPASSWD entry in the sudoers file
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%sudo\s*ALL='
      line: '%sudo ALL=(ALL) NOPASSWD: ALL'
      validate: '/usr/sbin/visudo -cf %s'
      
  - name: Disable PasswordAuthentication (ssh)
    lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      regexp: '^PasswordAuthentication'
      line: 'PasswordAuthentication no'
  - name: Disable root login (ssh)
    lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      regexp: '^PermitRootLogin'
      line: 'PermitRootLogin no'
  - name: Enable StrictMode (ssh)
    lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      regexp: '^StrictModes'
      line: 'StrictModes yes'
  - name: sshd neustarten
    service:
      name: sshd
      state: restarted

#
# eof ..
