---
# Update 'ansible' to version 2.4

- hosts: localhost
  become: yes
  tasks:
  - name: Add stretch-backports repro
    apt_repository:
      repo: deb http://ftp.de.debian.org/debian/ stretch-backports main
      state: present
      filename: 'ansible-stretch-backports'
  - name: Add stretch-backports repro (doc)
    apt_repository:
      repo: deb-src http://ftp.de.debian.org/debian/ stretch-backports main
      state: present
      filename: 'ansible-stretch-backports'
  - name: Update repositories cache and install "ansible" package
    #apt:
    #  name: ansible
    #  default_release: stretch-backports
    #  update_cache: yes
    command: apt-get install -t stretch-backports ansible
    register: result
 
  - name: Output apt
    debug: 
      var: result.output
      verbosity: 2

#
# eof ..
