---
# Update 'ansible' to version 2.4

- hosts: localhost
  become: yes
  tasks:
  - name: Add stretch-backports repro
    apt_repository:
      repo: deb http://ftp.de.debian.org/debian/ stretch-backports main
      state: present
  - name: Add stretch-backports repro (doc)
    apt_repository:
      repo: deb-src http://ftp.de.debian.org/debian/ stretch-backports main
      state: present
  - name: Update repositories cache and install "ansible" package
    apt:
      name: ansible
      update_cache: yes
  
#
# eof ..
